var link = [
    {
        name:'Tool',
        pic:'tool',
        url:'http://inav.com/tool.html',
        sort_n:10
    },
	{
		name:'新浪微博',
		pic:'1',
		url:'http://weibo.com/u/2562606833/home?wvr=5&sudaref=passport.weibo.com',
		sort_n:100
	},
    {
        name:'虎扑',
        pic:'2',
        url:'http://www.hupu.com/',
        sort_n:110
    },
    {
        name:'知乎',
        pic:'3',
        url:'https://www.zhihu.com/follow',
        sort_n:120
    },
    {
        name:'pptv体育',
        pic:'pptv',
        url:'http://sports.pptv.com/',
        sort_n:132
    },
    {
        name:'网易云音乐',
        pic:'38',
        url:'http://music.163.com/#',
        sort_n:140
    },
    {
        name:'腾讯',
        pic:'6',
        url:'http://www.qq.com/',
        sort_n:150
    },
    {
        name:'天猫',
        pic:'7',
        url:'https://www.tmall.com/',
        sort_n:160
    },
    {
        name:'stackoverflow',
        pic:'sf',
        url:'https://stackoverflow.com/',
        sort_n:165
    },
    {
        name:'quora',
        pic:'8',
        url:'https://www.quora.com/',
        sort_n:170
    },
    {
        name:'hao123',
        pic:'9',
        url:'https://www.hao123.com/?src=skycn_xzq',
        sort_n:280
    },
    {
        name:'QQ邮箱',
        pic:'11',
        url:'https://mail.qq.com/cgi-bin/frame_html?sid=FetLwN10kFNmOCJ1&r=ed30741f9cabf4df7ea21491aedcad96',
        sort_n:190
    },
    {
        name:'淘宝',
        pic:'12',
        url:'https://www.taobao.com/',
        sort_n:200
    },
    {
        name:'京东',
        pic:'13',
        url:'http://www.jd.com/',
        sort_n:210
    },
    {
        name:'京东金融',
        pic:'14',
        url:'http://gupiao.jd.com/optional-stock/',
        sort_n:125
    },
    /*{
        name:'自选新闻',
        pic:'news',
        url:'http://localhost:7777/index.php/Home/index/news',
        sort_n:122
    },*/
    {
        name:'印象笔记',
        pic:'15',
        url:'https://app.yinxiang.com/Home.action#n=ee349c91-d6bf-40fa-a7cc-428d23db6271&ses=4&sh=2&sds=5&',
        sort_n:230
    },
    {
        name:'有道云',
        pic:'16',
        url:'https://note.youdao.com/web/?notebook=%2F&sortMode=0&note=%2FSVR018730A41A884ACF812BAEB401946485%2Fweb1431446437572',
        sort_n:240
    },
    {
        name:'拉钩',
        pic:'18',
        url:'http://www.lagou.com/',
        sort_n:260
    },
    {
        name:'博客园',
        pic:'19',
        url:'http://www.cnblogs.com/',
        sort_n:390
    },
    {
        name:'华尔街日报',
        pic:'20',
        url:'https://wallstreetcn.com/',
        sort_n:180
    },
    {
        name:'segmentfault',
        pic:'21',
        url:'https://segmentfault.com/',
        sort_n:290
    },
    {
        name:'laravel',
        pic:'la',
        url:'https://laravel-china.org/topics',
        sort_n:175
    },
    {
        name:'youtube',
        pic:'24',
        url:'https://www.youtube.com/',
        sort_n:300
    },
    {
        name:'开发者头条',
        pic:'40',
        url:'http://toutiao.io/',
        sort_n:310
    },
    {
        name:'v2ex',
        pic:'25',
        url:'http://www.v2ex.com/',
        sort_n:185
    },
    {
        name:'百度云',
        pic:'26',
        url:'http://pan.baidu.com/disk/home#list/path=%2F',
        sort_n:330
    },
    {
        name:'reddit',
        pic:'36',
        url:'https://www.reddit.com/',
        sort_n:340
    },
    /*{
        name:'今日头条',
        pic:'37',
        url:'http://toutiao.com/',
        sort_n:350
    },*/
    {
        name:'虎嗅',
        pic:'22',
        url:'http://www.huxiu.com/',
        sort_n:360
    },
    {
        name:'Instagram',
        pic:'39',
        url:'https://www.instagram.com/',
        sort_n:380
    },
    {
        name:'格隆汇',
        pic:'glh',
        url:'http://www.gelonghui.com/default',
        sort_n:272
    },
    {
        name:'Twitter',
        pic:'tt',
        url:'https://twitter.com/',
        sort_n:352
    },
    {
        name:'雪球',
        pic:'xq',
        url:'https://xueqiu.com/today/',
        sort_n:271
    },
    /*{
        name:'集思录',
        pic:'27',
        url:'https://www.jisilu.cn/',
        sort_n:270
    }*/
]